/* tslint:disable */
/* eslint-disable */
/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BusinessEntities } from '../models';
// @ts-ignore
import { BusinessEntitiesCreateRequest } from '../models';
// @ts-ignore
import { BusinessEntitiesCreateRequestCustomFieldsValue } from '../models';
// @ts-ignore
import { BusinessEntitiesList } from '../models';
// @ts-ignore
import { BusinessEntitiesPatchRequest } from '../models';
// @ts-ignore
import { BusinessEntitiesPatchRequestCustomFieldsValue } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * BusinessEntitiesApi - axios parameter creator
 * @export
 */
export const BusinessEntitiesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns the created [Business Entity](https://developers.intellihr.io/docs/v1/).
         * @summary Create a new Business Entity
         * @param {BusinessEntitiesCreateRequest} businessEntitiesCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewEntity: async (businessEntitiesCreateRequest: BusinessEntitiesCreateRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'businessEntitiesCreateRequest' is not null or undefined
            assertParamExists('createNewEntity', 'businessEntitiesCreateRequest', businessEntitiesCreateRequest)
            const localVarPath = `/business-entities`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "apiKey", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: businessEntitiesCreateRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/business-entities',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(businessEntitiesCreateRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes the [Business Entity](https://developers.intellihr.io/docs/v1/)\'s by the given ID.
         * @summary Delete a Business Entity by ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteById: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/business-entities/{id}`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "apiKey", configuration })

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/business-entities/{id}',
                httpMethod: 'DELETE'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a single [Business Entity](https://developers.intellihr.io/docs/v1/) by its identifier.
         * @summary Find a Business Entity by ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findById: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/business-entities/{id}`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "apiKey", configuration })

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/business-entities/{id}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a list of all [Business Entities](https://developers.intellihr.io/docs/v1/).
         * @summary List all Business Entities
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAll: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/business-entities`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "apiKey", configuration })

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/business-entities',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the updated [Business Entity](https://developers.intellihr.io/docs/v1/).
         * @summary Update a Business Entity by ID
         * @param {BusinessEntitiesPatchRequest} businessEntitiesPatchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateById: async (businessEntitiesPatchRequest: BusinessEntitiesPatchRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'businessEntitiesPatchRequest' is not null or undefined
            assertParamExists('updateById', 'businessEntitiesPatchRequest', businessEntitiesPatchRequest)
            const localVarPath = `/business-entities/{id}`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "apiKey", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: businessEntitiesPatchRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/business-entities/{id}',
                httpMethod: 'PATCH'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(businessEntitiesPatchRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BusinessEntitiesApi - functional programming interface
 * @export
 */
export const BusinessEntitiesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BusinessEntitiesApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns the created [Business Entity](https://developers.intellihr.io/docs/v1/).
         * @summary Create a new Business Entity
         * @param {BusinessEntitiesApiCreateNewEntityRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createNewEntity(requestParameters: BusinessEntitiesApiCreateNewEntityRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BusinessEntities>> {
            const businessEntitiesCreateRequest: BusinessEntitiesCreateRequest = {
                name: requestParameters.name,
                code: requestParameters.code,
                legalName: requestParameters.legalName,
                number: requestParameters.number,
                isEnabled: requestParameters.isEnabled,
                customFields: requestParameters.customFields
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.createNewEntity(businessEntitiesCreateRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Deletes the [Business Entity](https://developers.intellihr.io/docs/v1/)\'s by the given ID.
         * @summary Delete a Business Entity by ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteById(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteById(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns a single [Business Entity](https://developers.intellihr.io/docs/v1/) by its identifier.
         * @summary Find a Business Entity by ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findById(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BusinessEntities>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findById(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns a list of all [Business Entities](https://developers.intellihr.io/docs/v1/).
         * @summary List all Business Entities
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAll(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BusinessEntitiesList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listAll(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns the updated [Business Entity](https://developers.intellihr.io/docs/v1/).
         * @summary Update a Business Entity by ID
         * @param {BusinessEntitiesApiUpdateByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateById(requestParameters: BusinessEntitiesApiUpdateByIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BusinessEntities>> {
            const businessEntitiesPatchRequest: BusinessEntitiesPatchRequest = {
                name: requestParameters.name,
                code: requestParameters.code,
                legalName: requestParameters.legalName,
                number: requestParameters.number,
                isEnabled: requestParameters.isEnabled,
                customFields: requestParameters.customFields
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateById(businessEntitiesPatchRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * BusinessEntitiesApi - factory interface
 * @export
 */
export const BusinessEntitiesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BusinessEntitiesApiFp(configuration)
    return {
        /**
         * Returns the created [Business Entity](https://developers.intellihr.io/docs/v1/).
         * @summary Create a new Business Entity
         * @param {BusinessEntitiesApiCreateNewEntityRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewEntity(requestParameters: BusinessEntitiesApiCreateNewEntityRequest, options?: AxiosRequestConfig): AxiosPromise<BusinessEntities> {
            return localVarFp.createNewEntity(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes the [Business Entity](https://developers.intellihr.io/docs/v1/)\'s by the given ID.
         * @summary Delete a Business Entity by ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteById(options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteById(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a single [Business Entity](https://developers.intellihr.io/docs/v1/) by its identifier.
         * @summary Find a Business Entity by ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findById(options?: AxiosRequestConfig): AxiosPromise<BusinessEntities> {
            return localVarFp.findById(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a list of all [Business Entities](https://developers.intellihr.io/docs/v1/).
         * @summary List all Business Entities
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAll(options?: AxiosRequestConfig): AxiosPromise<BusinessEntitiesList> {
            return localVarFp.listAll(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the updated [Business Entity](https://developers.intellihr.io/docs/v1/).
         * @summary Update a Business Entity by ID
         * @param {BusinessEntitiesApiUpdateByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateById(requestParameters: BusinessEntitiesApiUpdateByIdRequest, options?: AxiosRequestConfig): AxiosPromise<BusinessEntities> {
            return localVarFp.updateById(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createNewEntity operation in BusinessEntitiesApi.
 * @export
 * @interface BusinessEntitiesApiCreateNewEntityRequest
 */
export type BusinessEntitiesApiCreateNewEntityRequest = {
    
} & BusinessEntitiesCreateRequest

/**
 * Request parameters for updateById operation in BusinessEntitiesApi.
 * @export
 * @interface BusinessEntitiesApiUpdateByIdRequest
 */
export type BusinessEntitiesApiUpdateByIdRequest = {
    
} & BusinessEntitiesPatchRequest

/**
 * BusinessEntitiesApiGenerated - object-oriented interface
 * @export
 * @class BusinessEntitiesApiGenerated
 * @extends {BaseAPI}
 */
export class BusinessEntitiesApiGenerated extends BaseAPI {
    /**
     * Returns the created [Business Entity](https://developers.intellihr.io/docs/v1/).
     * @summary Create a new Business Entity
     * @param {BusinessEntitiesApiCreateNewEntityRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessEntitiesApiGenerated
     */
    public createNewEntity(requestParameters: BusinessEntitiesApiCreateNewEntityRequest, options?: AxiosRequestConfig) {
        return BusinessEntitiesApiFp(this.configuration).createNewEntity(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes the [Business Entity](https://developers.intellihr.io/docs/v1/)\'s by the given ID.
     * @summary Delete a Business Entity by ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessEntitiesApiGenerated
     */
    public deleteById(options?: AxiosRequestConfig) {
        return BusinessEntitiesApiFp(this.configuration).deleteById(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a single [Business Entity](https://developers.intellihr.io/docs/v1/) by its identifier.
     * @summary Find a Business Entity by ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessEntitiesApiGenerated
     */
    public findById(options?: AxiosRequestConfig) {
        return BusinessEntitiesApiFp(this.configuration).findById(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a list of all [Business Entities](https://developers.intellihr.io/docs/v1/).
     * @summary List all Business Entities
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessEntitiesApiGenerated
     */
    public listAll(options?: AxiosRequestConfig) {
        return BusinessEntitiesApiFp(this.configuration).listAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the updated [Business Entity](https://developers.intellihr.io/docs/v1/).
     * @summary Update a Business Entity by ID
     * @param {BusinessEntitiesApiUpdateByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessEntitiesApiGenerated
     */
    public updateById(requestParameters: BusinessEntitiesApiUpdateByIdRequest, options?: AxiosRequestConfig) {
        return BusinessEntitiesApiFp(this.configuration).updateById(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
