/* tslint:disable */
/* eslint-disable */
/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { QualificationStatuses } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * QualificationStatusesApi - axios parameter creator
 * @export
 */
export const QualificationStatusesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns a single [Qualification Status](https://developers.intellihr.io/docs/v1/) by its identifier.
         * @summary Find a Qualification Status by ID
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        findStatusById: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/qualification-statuses/{id}`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "apiKey", configuration })

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/qualification-statuses/{id}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QualificationStatusesApi - functional programming interface
 * @export
 */
export const QualificationStatusesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QualificationStatusesApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns a single [Qualification Status](https://developers.intellihr.io/docs/v1/) by its identifier.
         * @summary Find a Qualification Status by ID
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        async findStatusById(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QualificationStatuses>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findStatusById(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * QualificationStatusesApi - factory interface
 * @export
 */
export const QualificationStatusesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QualificationStatusesApiFp(configuration)
    return {
        /**
         * Returns a single [Qualification Status](https://developers.intellihr.io/docs/v1/) by its identifier.
         * @summary Find a Qualification Status by ID
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        findStatusById(options?: AxiosRequestConfig): AxiosPromise<QualificationStatuses> {
            return localVarFp.findStatusById(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QualificationStatusesApiGenerated - object-oriented interface
 * @export
 * @class QualificationStatusesApiGenerated
 * @extends {BaseAPI}
 */
export class QualificationStatusesApiGenerated extends BaseAPI {
    /**
     * Returns a single [Qualification Status](https://developers.intellihr.io/docs/v1/) by its identifier.
     * @summary Find a Qualification Status by ID
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof QualificationStatusesApiGenerated
     */
    public findStatusById(options?: AxiosRequestConfig) {
        return QualificationStatusesApiFp(this.configuration).findStatusById(options).then((request) => request(this.axios, this.basePath));
    }
}
