/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BusinessEntitiesCreateNewEntity403Response
 */
export interface BusinessEntitiesCreateNewEntity403Response {
    /**
     * 
     * @type {string}
     * @memberof BusinessEntitiesCreateNewEntity403Response
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessEntitiesCreateNewEntity403Response
     */
    'message'?: string;
    /**
     * HTTP Status Code for the error.
     * @type {number}
     * @memberof BusinessEntitiesCreateNewEntity403Response
     */
    'code'?: number;
    /**
     * 
     * @type {object}
     * @memberof BusinessEntitiesCreateNewEntity403Response
     */
    'errors'?: object;
}

