/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BusinessEntitiesCreateRequestCustomFieldsValueValueAnyOf2InnerJob } from './business-entities-create-request-custom-fields-value-value-any-of2-inner-job';
import { BusinessEntitiesCreateRequestCustomFieldsValueValueAnyOf2InnerPerson } from './business-entities-create-request-custom-fields-value-value-any-of2-inner-person';

/**
 * 
 * @export
 * @interface BusinessEntitiesCreateRequestCustomFieldsValueValueAnyOf2Inner
 */
export interface BusinessEntitiesCreateRequestCustomFieldsValueValueAnyOf2Inner {
    /**
     * 
     * @type {BusinessEntitiesCreateRequestCustomFieldsValueValueAnyOf2InnerPerson}
     * @memberof BusinessEntitiesCreateRequestCustomFieldsValueValueAnyOf2Inner
     */
    'person'?: BusinessEntitiesCreateRequestCustomFieldsValueValueAnyOf2InnerPerson;
    /**
     * 
     * @type {BusinessEntitiesCreateRequestCustomFieldsValueValueAnyOf2InnerJob}
     * @memberof BusinessEntitiesCreateRequestCustomFieldsValueValueAnyOf2Inner
     */
    'job'?: BusinessEntitiesCreateRequestCustomFieldsValueValueAnyOf2InnerJob;
}

