/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BusinessEntitiesListLinks } from './business-entities-list-links';
import { BusinessEntitiesListMeta } from './business-entities-list-meta';
import { BusinessEntity } from './business-entity';

/**
 * 
 * @export
 * @interface BusinessEntitiesList
 */
export interface BusinessEntitiesList {
    /**
     * 
     * @type {Array<BusinessEntity>}
     * @memberof BusinessEntitiesList
     */
    'data'?: Array<BusinessEntity>;
    /**
     * 
     * @type {BusinessEntitiesListMeta}
     * @memberof BusinessEntitiesList
     */
    'meta'?: BusinessEntitiesListMeta;
    /**
     * 
     * @type {BusinessEntitiesListLinks}
     * @memberof BusinessEntitiesList
     */
    'links'?: BusinessEntitiesListLinks;
}

