/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Links to other related resources.
 * @export
 * @interface BusinessEntitiesListLinks
 */
export interface BusinessEntitiesListLinks {
    /**
     * The current page URL
     * @type {string}
     * @memberof BusinessEntitiesListLinks
     */
    'self'?: string;
    /**
     * The first page URL
     * @type {string}
     * @memberof BusinessEntitiesListLinks
     */
    'first'?: string;
    /**
     * The previous page URL
     * @type {string}
     * @memberof BusinessEntitiesListLinks
     */
    'prev'?: string;
    /**
     * The next page URL
     * @type {string}
     * @memberof BusinessEntitiesListLinks
     */
    'next'?: string;
    /**
     * The last page URL
     * @type {string}
     * @memberof BusinessEntitiesListLinks
     */
    'last'?: string;
}

