/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BusinessUnitsCreateRequestCustomFieldsValueValue } from './business-units-create-request-custom-fields-value-value';

/**
 * Custom fields will be keyed by their api_name. Custom fields are not required, and only provided custom fields will be updated.
 * @export
 * @interface BusinessUnitsCreateRequestCustomFieldsValue
 */
export interface BusinessUnitsCreateRequestCustomFieldsValue {
    /**
     * 
     * @type {BusinessUnitsCreateRequestCustomFieldsValueValue}
     * @memberof BusinessUnitsCreateRequestCustomFieldsValue
     */
    'value'?: BusinessUnitsCreateRequestCustomFieldsValueValue | null;
}

