/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomFieldsResponse } from './custom-fields-response';

/**
 * 
 * @export
 * @interface BusinessEntityProperty
 */
export interface BusinessEntityProperty {
    /**
     * The identifier string for the [Business Entity](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof BusinessEntityProperty
     */
    'id'?: string;
    /**
     * Name given to this [Business Entity](https://developers.intellihr.io/docs/v1/). This name would normally be shown to users of the system.
     * @type {string}
     * @memberof BusinessEntityProperty
     */
    'name'?: string;
    /**
     * Code given to this [Business Entity](https://developers.intellihr.io/docs/v1/)
     * @type {string}
     * @memberof BusinessEntityProperty
     */
    'code'?: string;
    /**
     * Legal name can be different from the name presented to a user. Usually used for administrative tasks.
     * @type {string}
     * @memberof BusinessEntityProperty
     */
    'legalName'?: string;
    /**
     * Legally registered [Business Entity](https://developers.intellihr.io/docs/v1/) number, e.g. in Australia this might be the ABN, or in America the RN.
     * @type {string}
     * @memberof BusinessEntityProperty
     */
    'number'?: string;
    /**
     * Specifies whether users can select this [Business Entity](https://developers.intellihr.io/docs/v1/) in dropdowns.
     * @type {boolean}
     * @memberof BusinessEntityProperty
     */
    'isEnabled'?: boolean;
    /**
     * The custom field values for this [Business Entity](https://developers.intellihr.io/docs/v1/)
     * @type {CustomFieldsResponse}
     * @memberof BusinessEntityProperty
     */
    'customFields'?: CustomFieldsResponse;
}

