/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomFieldDefinitionPropertyDescription } from './custom-field-definition-property-description';
import { ThePeopleDropdownDefinitionOfTheCustomFieldDefinitionProperty1 } from './the-people-dropdown-definition-of-the-custom-field-definition-property1';
import { TheSelectDefinitionOfTheCustomFieldDefinitionProperty1 } from './the-select-definition-of-the-custom-field-definition-property1';

/**
 * 
 * @export
 * @interface CustomFieldDefinitionPatchRequest
 */
export interface CustomFieldDefinitionPatchRequest {
    /**
     * 
     * @type {CustomFieldDefinitionPropertyDescription}
     * @memberof CustomFieldDefinitionPatchRequest
     */
    'description'?: CustomFieldDefinitionPropertyDescription;
    /**
     * Name given to this [Custom Field Definition](https://developers.intellihr.io/docs/v1/). This name would normally be shown to users of the system.
     * @type {string}
     * @memberof CustomFieldDefinitionPatchRequest
     */
    'name'?: string;
    /**
     * Whether or not this [Custom Field Definition](https://developers.intellihr.io/docs/v1/) is enabled to be used.
     * @type {boolean}
     * @memberof CustomFieldDefinitionPatchRequest
     */
    'isEnabled'?: boolean;
    /**
     * Whether or not this [Custom Field Definition](https://developers.intellihr.io/docs/v1/) is marked as sensitive information.
     * @type {boolean}
     * @memberof CustomFieldDefinitionPatchRequest
     */
    'isSensitive'?: boolean;
    /**
     * 
     * @type {TheSelectDefinitionOfTheCustomFieldDefinitionProperty1}
     * @memberof CustomFieldDefinitionPatchRequest
     */
    'selectDefinition'?: TheSelectDefinitionOfTheCustomFieldDefinitionProperty1;
    /**
     * 
     * @type {ThePeopleDropdownDefinitionOfTheCustomFieldDefinitionProperty1}
     * @memberof CustomFieldDefinitionPatchRequest
     */
    'peopleDropdownDefinition'?: ThePeopleDropdownDefinitionOfTheCustomFieldDefinitionProperty1;
}

