/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomFieldDefinition } from './custom-field-definition';
import { CustomFieldDefinitionsListLinks } from './custom-field-definitions-list-links';
import { CustomFieldDefinitionsListMeta } from './custom-field-definitions-list-meta';

/**
 * 
 * @export
 * @interface CustomFieldDefinitionsList
 */
export interface CustomFieldDefinitionsList {
    /**
     * 
     * @type {Array<CustomFieldDefinition>}
     * @memberof CustomFieldDefinitionsList
     */
    'data'?: Array<CustomFieldDefinition>;
    /**
     * 
     * @type {CustomFieldDefinitionsListMeta}
     * @memberof CustomFieldDefinitionsList
     */
    'meta'?: CustomFieldDefinitionsListMeta;
    /**
     * 
     * @type {CustomFieldDefinitionsListLinks}
     * @memberof CustomFieldDefinitionsList
     */
    'links'?: CustomFieldDefinitionsListLinks;
}

