/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DataPropertyInnerEmergencyContactEmail } from './data-property-inner-emergency-contact-email';
import { DataPropertyInnerEmergencyContactName } from './data-property-inner-emergency-contact-name';
import { DataPropertyInnerEmergencyContactPhone } from './data-property-inner-emergency-contact-phone';
import { DataPropertyInnerEmergencyContactRelationship } from './data-property-inner-emergency-contact-relationship';

/**
 * The details for this [Person\'s](https://developers.intellihr.io/docs/v1/) emergency contact.
 * @export
 * @interface DataPropertyInnerEmergencyContact
 */
export interface DataPropertyInnerEmergencyContact {
    /**
     * 
     * @type {DataPropertyInnerEmergencyContactName}
     * @memberof DataPropertyInnerEmergencyContact
     */
    'name'?: DataPropertyInnerEmergencyContactName;
    /**
     * 
     * @type {DataPropertyInnerEmergencyContactRelationship}
     * @memberof DataPropertyInnerEmergencyContact
     */
    'relationship'?: DataPropertyInnerEmergencyContactRelationship;
    /**
     * 
     * @type {DataPropertyInnerEmergencyContactPhone}
     * @memberof DataPropertyInnerEmergencyContact
     */
    'phone'?: DataPropertyInnerEmergencyContactPhone;
    /**
     * 
     * @type {DataPropertyInnerEmergencyContactEmail}
     * @memberof DataPropertyInnerEmergencyContact
     */
    'email'?: DataPropertyInnerEmergencyContactEmail;
}

