/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DataPropertyInnerPrimaryEmailAddressOneOf
 */
export interface DataPropertyInnerPrimaryEmailAddressOneOf {
    /**
     * The actual email address.
     * @type {string}
     * @memberof DataPropertyInnerPrimaryEmailAddressOneOf
     */
    'email'?: string;
    /**
     * Denotes whether this email is personal or a work email.
     * @type {boolean}
     * @memberof DataPropertyInnerPrimaryEmailAddressOneOf
     */
    'isPersonal'?: boolean;
}

