/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DataPropertyInnerUserAccountOneOfUserPermissionGroupsInnerPermissionGroup } from './data-property-inner-user-account-one-of-user-permission-groups-inner-permission-group';

/**
 * 
 * @export
 * @interface DataPropertyInnerUserAccountOneOfUserPermissionGroupsInner
 */
export interface DataPropertyInnerUserAccountOneOfUserPermissionGroupsInner {
    /**
     * The identifier string for the User Permission Group.
     * @type {string}
     * @memberof DataPropertyInnerUserAccountOneOfUserPermissionGroupsInner
     */
    'id'?: string;
    /**
     * 
     * @type {DataPropertyInnerUserAccountOneOfUserPermissionGroupsInnerPermissionGroup}
     * @memberof DataPropertyInnerUserAccountOneOfUserPermissionGroupsInner
     */
    'permissionGroup'?: DataPropertyInnerUserAccountOneOfUserPermissionGroupsInnerPermissionGroup;
}

