/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DataPropertyInnerPrimaryEmailAddressOneOf } from './data-property-inner-primary-email-address-one-of';

/**
 * @type DataPropertyInnerPrimaryEmailAddress
 * Information about this Person\'s primary email address, or null if they have no email information.
 * @export
 */
export type DataPropertyInnerPrimaryEmailAddress = DataPropertyInnerPrimaryEmailAddressOneOf | Null;


