/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmploymentConditionProperty } from './employment-condition-property';
import { EmploymentConditionsMeta } from './employment-conditions-meta';

/**
 * 
 * @export
 * @interface EmploymentConditions
 */
export interface EmploymentConditions {
    /**
     * 
     * @type {EmploymentConditionProperty}
     * @memberof EmploymentConditions
     */
    'data'?: EmploymentConditionProperty;
    /**
     * 
     * @type {EmploymentConditionsMeta}
     * @memberof EmploymentConditions
     */
    'meta'?: EmploymentConditionsMeta;
}

