/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FormPropertySubmitterOneOfJob } from './form-property-submitter-one-of-job';
import { FormPropertySubmitterOneOfPerson } from './form-property-submitter-one-of-person';

/**
 * 
 * @export
 * @interface FormPropertySubmitterOneOf
 */
export interface FormPropertySubmitterOneOf {
    /**
     * 
     * @type {FormPropertySubmitterOneOfJob}
     * @memberof FormPropertySubmitterOneOf
     */
    'job'?: FormPropertySubmitterOneOfJob;
    /**
     * 
     * @type {FormPropertySubmitterOneOfPerson}
     * @memberof FormPropertySubmitterOneOf
     */
    'person'?: FormPropertySubmitterOneOfPerson;
}

