/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExtendedLeavePropertyPersonEmployeeNumber } from './extended-leave-property-person-employee-number';
import { FormPropertySubmitterOneOfPersonEmailAddressesInner } from './form-property-submitter-one-of-person-email-addresses-inner';

/**
 * [Person](https://developers.intellihr.io/docs/v1/) to whom this [Form](https://developers.intellihr.io/docs/v1/) expects a response from. Note that this person value has been deprecated, you should now reference the person object within the respondent field.
 * @export
 * @interface FormPropertySubmitterOneOfPerson
 */
export interface FormPropertySubmitterOneOfPerson {
    /**
     * The identifier string for the [Person](https://developers.intellihr.io/docs/v1/) to whom this [Form](https://developers.intellihr.io/docs/v1/) belongs.
     * @type {string}
     * @memberof FormPropertySubmitterOneOfPerson
     */
    'id'?: string;
    /**
     * Name to display throughout the system for this [Person](https://developers.intellihr.io/docs/v1/). Generally follows the pattern preferredName (firstName) lastName, but can be configured on a tenant-wide basis to be a different format.
     * @type {string}
     * @memberof FormPropertySubmitterOneOfPerson
     */
    'displayName'?: string;
    /**
     * An array of email addresses that belong to this Person.
     * @type {Array<FormPropertySubmitterOneOfPersonEmailAddressesInner>}
     * @memberof FormPropertySubmitterOneOfPerson
     */
    'emailAddresses'?: Array<FormPropertySubmitterOneOfPersonEmailAddressesInner>;
    /**
     * 
     * @type {ExtendedLeavePropertyPersonEmployeeNumber}
     * @memberof FormPropertySubmitterOneOfPerson
     */
    'employeeNumber'?: ExtendedLeavePropertyPersonEmployeeNumber;
    /**
     * An autogenerated number that uniquely identifies a [Person](https://developers.intellihr.io/docs/v1/) in intelliHR. It may be hidden in the system\'s UI depending upon your tenant\'s configuration.
     * @type {number}
     * @memberof FormPropertySubmitterOneOfPerson
     */
    'autoIncrementIntellihrId'?: number;
    /**
     * Link on the public api to get more information on this piece of data.
     * @type {string}
     * @memberof FormPropertySubmitterOneOfPerson
     */
    'link'?: string;
}

