/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FormPropertySubjectJob } from './form-property-subject-job';
import { FormPropertySubjectPerson } from './form-property-subject-person';

/**
 * The subject that this [Form](https://developers.intellihr.io/docs/v1/) is about
 * @export
 * @interface FormPropertySubject
 */
export interface FormPropertySubject {
    /**
     * 
     * @type {FormPropertySubjectJob}
     * @memberof FormPropertySubject
     */
    'job'?: FormPropertySubjectJob;
    /**
     * 
     * @type {FormPropertySubjectPerson}
     * @memberof FormPropertySubject
     */
    'person'?: FormPropertySubjectPerson;
}

