/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobCreateRequestCustomFieldsValueValueAnyOfInnerJob } from './job-create-request-custom-fields-value-value-any-of-inner-job';
import { JobCreateRequestCustomFieldsValueValueAnyOfInnerPerson } from './job-create-request-custom-fields-value-value-any-of-inner-person';

/**
 * 
 * @export
 * @interface JobCreateRequestCustomFieldsValueValueAnyOfInner
 */
export interface JobCreateRequestCustomFieldsValueValueAnyOfInner {
    /**
     * 
     * @type {JobCreateRequestCustomFieldsValueValueAnyOfInnerPerson}
     * @memberof JobCreateRequestCustomFieldsValueValueAnyOfInner
     */
    'person'?: JobCreateRequestCustomFieldsValueValueAnyOfInnerPerson;
    /**
     * 
     * @type {JobCreateRequestCustomFieldsValueValueAnyOfInnerJob}
     * @memberof JobCreateRequestCustomFieldsValueValueAnyOfInner
     */
    'job'?: JobCreateRequestCustomFieldsValueValueAnyOfInnerJob;
}

