/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomFieldsResponse } from './custom-fields-response';
import { JobEndPatchResponseDataJobFte } from './job-end-patch-response-data-job-fte';
import { JobEndPatchResponseDataJobTurnoverReason } from './job-end-patch-response-data-job-turnover-reason';
import { JobEndPatchResponseDataJobTurnoverType } from './job-end-patch-response-data-job-turnover-type';
import { JobEndRemoveResponseDataJobBusinessEntity } from './job-end-remove-response-data-job-business-entity';
import { JobEndRemoveResponseDataJobBusinessUnit } from './job-end-remove-response-data-job-business-unit';
import { JobEndRemoveResponseDataJobCommentsInner } from './job-end-remove-response-data-job-comments-inner';
import { JobEndRemoveResponseDataJobCreatedBy } from './job-end-remove-response-data-job-created-by';
import { JobEndRemoveResponseDataJobEmploymentCondition } from './job-end-remove-response-data-job-employment-condition';
import { JobEndRemoveResponseDataJobEstablishment } from './job-end-remove-response-data-job-establishment';
import { JobEndRemoveResponseDataJobExtendedLeave } from './job-end-remove-response-data-job-extended-leave';
import { JobEndRemoveResponseDataJobLastestJobChangeComment } from './job-end-remove-response-data-job-lastest-job-change-comment';
import { JobEndRemoveResponseDataJobLocation } from './job-end-remove-response-data-job-location';
import { JobEndRemoveResponseDataJobPayGrade } from './job-end-remove-response-data-job-pay-grade';
import { JobEndRemoveResponseDataJobPerson } from './job-end-remove-response-data-job-person';
import { JobEndRemoveResponseDataJobPositionTitle } from './job-end-remove-response-data-job-position-title';
import { JobEndRemoveResponseDataJobRecruitment } from './job-end-remove-response-data-job-recruitment';
import { JobEndRemoveResponseDataJobRemunerationSchedule } from './job-end-remove-response-data-job-remuneration-schedule';
import { JobEndRemoveResponseDataJobSupervisorJob } from './job-end-remove-response-data-job-supervisor-job';
import { JobEndRemoveResponseDataJobSupervisorPerson } from './job-end-remove-response-data-job-supervisor-person';
import { JobEndRemoveResponseDataJobUpdatedBy } from './job-end-remove-response-data-job-updated-by';
import { RFC3339DatetimeProperty3 } from './rfc3339-datetime-property3';

/**
 * 
 * @export
 * @interface JobEndRemoveResponseDataJob
 */
export interface JobEndRemoveResponseDataJob {
    /**
     * The identifier string for the [Job](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof JobEndRemoveResponseDataJob
     */
    'id'?: string;
    /**
     * 
     * @type {JobEndRemoveResponseDataJobPerson}
     * @memberof JobEndRemoveResponseDataJob
     */
    'person'?: JobEndRemoveResponseDataJobPerson;
    /**
     * 
     * @type {JobEndRemoveResponseDataJobRecruitment}
     * @memberof JobEndRemoveResponseDataJob
     */
    'recruitment'?: JobEndRemoveResponseDataJobRecruitment;
    /**
     * 
     * @type {JobEndRemoveResponseDataJobExtendedLeave}
     * @memberof JobEndRemoveResponseDataJob
     */
    'extendedLeave'?: JobEndRemoveResponseDataJobExtendedLeave;
    /**
     * 
     * @type {JobEndRemoveResponseDataJobLocation}
     * @memberof JobEndRemoveResponseDataJob
     */
    'location'?: JobEndRemoveResponseDataJobLocation;
    /**
     * 
     * @type {JobEndRemoveResponseDataJobPayGrade}
     * @memberof JobEndRemoveResponseDataJob
     */
    'payGrade'?: JobEndRemoveResponseDataJobPayGrade;
    /**
     * 
     * @type {JobEndRemoveResponseDataJobBusinessUnit}
     * @memberof JobEndRemoveResponseDataJob
     */
    'businessUnit'?: JobEndRemoveResponseDataJobBusinessUnit;
    /**
     * 
     * @type {JobEndRemoveResponseDataJobBusinessEntity}
     * @memberof JobEndRemoveResponseDataJob
     */
    'businessEntity'?: JobEndRemoveResponseDataJobBusinessEntity;
    /**
     * 
     * @type {JobEndRemoveResponseDataJobEstablishment}
     * @memberof JobEndRemoveResponseDataJob
     */
    'establishment'?: JobEndRemoveResponseDataJobEstablishment;
    /**
     * 
     * @type {JobEndRemoveResponseDataJobSupervisorJob}
     * @memberof JobEndRemoveResponseDataJob
     */
    'supervisorJob'?: JobEndRemoveResponseDataJobSupervisorJob;
    /**
     * 
     * @type {JobEndRemoveResponseDataJobSupervisorPerson}
     * @memberof JobEndRemoveResponseDataJob
     */
    'supervisorPerson'?: JobEndRemoveResponseDataJobSupervisorPerson;
    /**
     * 
     * @type {JobEndRemoveResponseDataJobEmploymentCondition}
     * @memberof JobEndRemoveResponseDataJob
     */
    'employmentCondition'?: JobEndRemoveResponseDataJobEmploymentCondition;
    /**
     * 
     * @type {JobEndRemoveResponseDataJobRemunerationSchedule}
     * @memberof JobEndRemoveResponseDataJob
     */
    'remunerationSchedule'?: JobEndRemoveResponseDataJobRemunerationSchedule;
    /**
     * The name of this [Job](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof JobEndRemoveResponseDataJob
     */
    'name'?: string;
    /**
     * 
     * @type {JobEndRemoveResponseDataJobPositionTitle}
     * @memberof JobEndRemoveResponseDataJob
     */
    'positionTitle'?: JobEndRemoveResponseDataJobPositionTitle;
    /**
     * 
     * @type {JobEndPatchResponseDataJobFte}
     * @memberof JobEndRemoveResponseDataJob
     */
    'fte'?: JobEndPatchResponseDataJobFte;
    /**
     * An array of comment objects that annotate the reason for [Job](https://developers.intellihr.io/docs/v1/) changes. Will be an empty array when there has been no updates to the Job.
     * @type {Array<JobEndRemoveResponseDataJobCommentsInner>}
     * @memberof JobEndRemoveResponseDataJob
     */
    'comments'?: Array<JobEndRemoveResponseDataJobCommentsInner>;
    /**
     * 
     * @type {JobEndRemoveResponseDataJobLastestJobChangeComment}
     * @memberof JobEndRemoveResponseDataJob
     */
    'lastestJobChangeComment'?: JobEndRemoveResponseDataJobLastestJobChangeComment;
    /**
     * The [Work Class](https://developers.intellihr.io/docs/v1/) of this [Job](https://developers.intellihr.io/docs/v1/). This is extra details about the [Work Type](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof JobEndRemoveResponseDataJob
     */
    'workClass'?: string;
    /**
     * This is the [Work Classification](https://developers.intellihr.io/docs/v1/) for this [Job](https://developers.intellihr.io/docs/v1/), it is used to differentiate between full-time and part time employees vs unpaid volunteers. Enum: `Permanent`, `Fixed Contract`, `Unpaid`, `Temporary/Casual`, `Independent Contract`.
     * @type {string}
     * @memberof JobEndRemoveResponseDataJob
     */
    'workType'?: string;
    /**
     * Whether this job is the primary job on the [Person](https://developers.intellihr.io/docs/v1/). Only one job on a [Person](https://developers.intellihr.io/docs/v1/) can be primary at a time.
     * @type {boolean}
     * @memberof JobEndRemoveResponseDataJob
     */
    'isPrimaryJob'?: boolean;
    /**
     * The current status of this job within this organisation. Enum: `Past Job`, `Future Job`, `Ending Job`, `Current Job`.
     * @type {string}
     * @memberof JobEndRemoveResponseDataJob
     */
    'jobStatus'?: string;
    /**
     * 
     * @type {JobEndRemoveResponseDataJobCreatedBy}
     * @memberof JobEndRemoveResponseDataJob
     */
    'createdBy'?: JobEndRemoveResponseDataJobCreatedBy;
    /**
     * 
     * @type {JobEndRemoveResponseDataJobUpdatedBy}
     * @memberof JobEndRemoveResponseDataJob
     */
    'updatedBy'?: JobEndRemoveResponseDataJobUpdatedBy;
    /**
     * The start date of the current position the person is in. The gap between the `companyStartDate` and `positionStartDate` will be filled with \"Previous position title\" historical records, to correctly depict the person as having no information recorded for old job positions. This date will follow the format defined by [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6).   YYYY-MM-DD date formatting is also supported, although by using this format the date will be stored as the start of day in UTC time, not the requesting tenants timezone.
     * @type {string}
     * @memberof JobEndRemoveResponseDataJob
     */
    'positionStartDate'?: string;
    /**
     * The date this [Job](https://developers.intellihr.io/docs/v1/) started or will start within the organisation. This date will follow the format defined by [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6).
     * @type {string}
     * @memberof JobEndRemoveResponseDataJob
     */
    'companyStartDate'?: string;
    /**
     * 
     * @type {RFC3339DatetimeProperty3}
     * @memberof JobEndRemoveResponseDataJob
     */
    'companyEndDate'?: RFC3339DatetimeProperty3;
    /**
     * Whether the end date has been finalised within the intelliHR application.
     * @type {boolean}
     * @memberof JobEndRemoveResponseDataJob
     */
    'isEndDateConfirmed'?: boolean;
    /**
     * 
     * @type {JobEndPatchResponseDataJobTurnoverType}
     * @memberof JobEndRemoveResponseDataJob
     */
    'turnoverType'?: JobEndPatchResponseDataJobTurnoverType;
    /**
     * 
     * @type {JobEndPatchResponseDataJobTurnoverReason}
     * @memberof JobEndRemoveResponseDataJob
     */
    'turnoverReason'?: JobEndPatchResponseDataJobTurnoverReason;
    /**
     * The custom field values for this Job
     * @type {CustomFieldsResponse}
     * @memberof JobEndRemoveResponseDataJob
     */
    'customFields'?: CustomFieldsResponse;
    /**
     * When this record was created. This date will follow the format defined by [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6).
     * @type {string}
     * @memberof JobEndRemoveResponseDataJob
     */
    'createdAt'?: string;
}

