/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomFieldsResponse } from './custom-fields-response';

/**
 * The [Job\'s](https://developers.intellihr.io/docs/v1/) current [Business Entity](https://developers.intellihr.io/docs/v1/) in the system.
 * @export
 * @interface JobProperty3BusinessEntity
 */
export interface JobProperty3BusinessEntity {
    /**
     * The identifier string for the [Business Entity](https://developers.intellihr.io/docs/v1/) of this [Job](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof JobProperty3BusinessEntity
     */
    'id'?: string;
    /**
     * Name given to this [Business Entity](https://developers.intellihr.io/docs/v1/). This name would normally be shown to users of the system.
     * @type {string}
     * @memberof JobProperty3BusinessEntity
     */
    'name'?: string;
    /**
     * Code given to this [Business Entity](https://developers.intellihr.io/docs/v1/).
     * @type {any}
     * @memberof JobProperty3BusinessEntity
     */
    'code'?: any;
    /**
     * Link on the public api to get more information on this piece of data.
     * @type {string}
     * @memberof JobProperty3BusinessEntity
     */
    'link'?: string;
    /**
     * The custom field values for this Business Unit
     * @type {CustomFieldsResponse}
     * @memberof JobProperty3BusinessEntity
     */
    'customFields'?: CustomFieldsResponse;
}

