/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobRequirementGroupPropertyLibraryItemsInner } from './job-requirement-group-property-library-items-inner';

/**
 * 
 * @export
 * @interface JobRequirementGroupProperty
 */
export interface JobRequirementGroupProperty {
    /**
     * The identifier string for the [Job Requirement Group](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof JobRequirementGroupProperty
     */
    'id'?: string;
    /**
     * The issue date of the [Job Requirement Group](https://developers.intellihr.io/docs/v1/)
     * @type {string}
     * @memberof JobRequirementGroupProperty
     */
    'name'?: string;
    /**
     * The library items assigned to this [Job Requirement Group](https://developers.intellihr.io/docs/v1/).
     * @type {Array<JobRequirementGroupPropertyLibraryItemsInner>}
     * @memberof JobRequirementGroupProperty
     */
    'libraryItems'?: Array<JobRequirementGroupPropertyLibraryItemsInner>;
    /**
     * The count of how many times this job requirement group is being used in job requirements
     * @type {number}
     * @memberof JobRequirementGroupProperty
     */
    'jobRequirementUsageCount'?: number;
}

