/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * [Business Entity](https://developers.intellihr.io/docs/v1/) to which this [Job](https://developers.intellihr.io/docs/v1/) belongs. This [Business Entity](https://developers.intellihr.io/docs/v1/) is specified as a search object, which will match the business entity which best fits the keys for this object. Multiple keys can be used together to further narrow search results.
 * @export
 * @interface JobCreateRequestBusinessEntity
 */
export interface JobCreateRequestBusinessEntity {
    /**
     * The identifier string for the [Business Entity](https://developers.intellihr.io/docs/v1/) to which this [Job](https://developers.intellihr.io/docs/v1/) belongs.
     * @type {string}
     * @memberof JobCreateRequestBusinessEntity
     */
    'id'?: string;
    /**
     * Name given to this [Business Entity](https://developers.intellihr.io/docs/v1/). This name would normally be shown to users of the system.
     * @type {string}
     * @memberof JobCreateRequestBusinessEntity
     */
    'name'?: string;
    /**
     * Legal name of [Business Entity](https://developers.intellihr.io/docs/v1/). Usually used for administrative tasks.
     * @type {string}
     * @memberof JobCreateRequestBusinessEntity
     */
    'legalName'?: string;
    /**
     * Legally registered [Business Entity](https://developers.intellihr.io/docs/v1/) number, e.g. in Australia this might be the ABN, or in America the RN.
     * @type {string}
     * @memberof JobCreateRequestBusinessEntity
     */
    'number'?: string;
}

