/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobProperty3ExtendedLeaveOneOfTypeOneOf } from './job-property3-extended-leave-one-of-type-one-of';

/**
 * @type JobProperty3ExtendedLeaveOneOfType
 * The [Extended Leave Type](https://developers.intellihr.io/docs/v1/) for this leave record, or null if the person was not on leave for these dates
 * @export
 */
export type JobProperty3ExtendedLeaveOneOfType = JobProperty3ExtendedLeaveOneOfTypeOneOf | Null;


