/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobEndPatchResponseDataJobCreatedByOneOf } from './job-end-patch-response-data-job-created-by-one-of';

/**
 * @type JobEndPatchResponseDataJobCreatedBy
 * The [User](https://developers.intellihr.io/docs/v1/) who created this job. May be null for old [Jobs](https://developers.intellihr.io/docs/v1/). This field will remain null for API created jobs.
 * @export
 */
export type JobEndPatchResponseDataJobCreatedBy = JobEndPatchResponseDataJobCreatedByOneOf | Null;


