/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmploymentConditionPropertyAwardName } from './employment-condition-property-award-name';

/**
 * The [Employment Condition](https://developers.intellihr.io/docs/v1/) this job is being paid under.
 * @export
 * @interface JobEndPatchResponseDataJobEmploymentConditionOneOf
 */
export interface JobEndPatchResponseDataJobEmploymentConditionOneOf {
    /**
     * The identifier string for the [Employment Condition](https://developers.intellihr.io/docs/v1/) of this Remuneration Schedule.
     * @type {string}
     * @memberof JobEndPatchResponseDataJobEmploymentConditionOneOf
     */
    'id'?: string;
    /**
     * The start date of the attribute, or null for start of job. This date will follow the format defined by [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6).   YYYY-MM-DD date formatting is also supported, although by using this format the date will be stored as the start of day in UTC time, not the requesting tenants timezone.
     * @type {any}
     * @memberof JobEndPatchResponseDataJobEmploymentConditionOneOf
     */
    'startDate'?: any;
    /**
     * The end date of the attribute, or null for end of job/time. This date will follow the format defined by [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6).   YYYY-MM-DD date formatting is also supported, although by using this format the date will be stored as the start of day in UTC time, not the requesting tenants timezone.
     * @type {any}
     * @memberof JobEndPatchResponseDataJobEmploymentConditionOneOf
     */
    'endDate'?: any;
    /**
     * Name given to this [Employment Condition](https://developers.intellihr.io/docs/v1/). This name would normally be shown to users of the system.
     * @type {string}
     * @memberof JobEndPatchResponseDataJobEmploymentConditionOneOf
     */
    'name'?: string;
    /**
     * 
     * @type {EmploymentConditionPropertyAwardName}
     * @memberof JobEndPatchResponseDataJobEmploymentConditionOneOf
     */
    'awardName'?: EmploymentConditionPropertyAwardName;
    /**
     * Link on the public api to get more information on this piece of data.
     * @type {string}
     * @memberof JobEndPatchResponseDataJobEmploymentConditionOneOf
     */
    'link'?: string;
}

