/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomFieldsResponse } from './custom-fields-response';
import { JobEndPatchResponseDataJobBusinessEntity } from './job-end-patch-response-data-job-business-entity';
import { JobEndPatchResponseDataJobBusinessUnit } from './job-end-patch-response-data-job-business-unit';
import { JobEndPatchResponseDataJobCommentsInner } from './job-end-patch-response-data-job-comments-inner';
import { JobEndPatchResponseDataJobCreatedBy } from './job-end-patch-response-data-job-created-by';
import { JobEndPatchResponseDataJobEmploymentCondition } from './job-end-patch-response-data-job-employment-condition';
import { JobEndPatchResponseDataJobEstablishment } from './job-end-patch-response-data-job-establishment';
import { JobEndPatchResponseDataJobExtendedLeave } from './job-end-patch-response-data-job-extended-leave';
import { JobEndPatchResponseDataJobFte } from './job-end-patch-response-data-job-fte';
import { JobEndPatchResponseDataJobLastestJobChangeComment } from './job-end-patch-response-data-job-lastest-job-change-comment';
import { JobEndPatchResponseDataJobLocation } from './job-end-patch-response-data-job-location';
import { JobEndPatchResponseDataJobPayGrade } from './job-end-patch-response-data-job-pay-grade';
import { JobEndPatchResponseDataJobPerson } from './job-end-patch-response-data-job-person';
import { JobEndPatchResponseDataJobPositionTitle } from './job-end-patch-response-data-job-position-title';
import { JobEndPatchResponseDataJobRecruitment } from './job-end-patch-response-data-job-recruitment';
import { JobEndPatchResponseDataJobRemunerationSchedule } from './job-end-patch-response-data-job-remuneration-schedule';
import { JobEndPatchResponseDataJobSupervisorJob } from './job-end-patch-response-data-job-supervisor-job';
import { JobEndPatchResponseDataJobSupervisorPerson } from './job-end-patch-response-data-job-supervisor-person';
import { JobEndPatchResponseDataJobTurnoverReason } from './job-end-patch-response-data-job-turnover-reason';
import { JobEndPatchResponseDataJobTurnoverType } from './job-end-patch-response-data-job-turnover-type';
import { JobEndPatchResponseDataJobUpdatedBy } from './job-end-patch-response-data-job-updated-by';
import { RFC3339DatetimeProperty3 } from './rfc3339-datetime-property3';

/**
 * 
 * @export
 * @interface JobEndPatchResponseDataJob
 */
export interface JobEndPatchResponseDataJob {
    /**
     * The identifier string for the [Job](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof JobEndPatchResponseDataJob
     */
    'id'?: string;
    /**
     * 
     * @type {JobEndPatchResponseDataJobPerson}
     * @memberof JobEndPatchResponseDataJob
     */
    'person'?: JobEndPatchResponseDataJobPerson;
    /**
     * 
     * @type {JobEndPatchResponseDataJobRecruitment}
     * @memberof JobEndPatchResponseDataJob
     */
    'recruitment'?: JobEndPatchResponseDataJobRecruitment;
    /**
     * 
     * @type {JobEndPatchResponseDataJobExtendedLeave}
     * @memberof JobEndPatchResponseDataJob
     */
    'extendedLeave'?: JobEndPatchResponseDataJobExtendedLeave;
    /**
     * 
     * @type {JobEndPatchResponseDataJobLocation}
     * @memberof JobEndPatchResponseDataJob
     */
    'location'?: JobEndPatchResponseDataJobLocation;
    /**
     * 
     * @type {JobEndPatchResponseDataJobPayGrade}
     * @memberof JobEndPatchResponseDataJob
     */
    'payGrade'?: JobEndPatchResponseDataJobPayGrade;
    /**
     * 
     * @type {JobEndPatchResponseDataJobBusinessUnit}
     * @memberof JobEndPatchResponseDataJob
     */
    'businessUnit'?: JobEndPatchResponseDataJobBusinessUnit;
    /**
     * 
     * @type {JobEndPatchResponseDataJobBusinessEntity}
     * @memberof JobEndPatchResponseDataJob
     */
    'businessEntity'?: JobEndPatchResponseDataJobBusinessEntity;
    /**
     * 
     * @type {JobEndPatchResponseDataJobEstablishment}
     * @memberof JobEndPatchResponseDataJob
     */
    'establishment'?: JobEndPatchResponseDataJobEstablishment;
    /**
     * 
     * @type {JobEndPatchResponseDataJobSupervisorJob}
     * @memberof JobEndPatchResponseDataJob
     */
    'supervisorJob'?: JobEndPatchResponseDataJobSupervisorJob;
    /**
     * 
     * @type {JobEndPatchResponseDataJobSupervisorPerson}
     * @memberof JobEndPatchResponseDataJob
     */
    'supervisorPerson'?: JobEndPatchResponseDataJobSupervisorPerson;
    /**
     * 
     * @type {JobEndPatchResponseDataJobEmploymentCondition}
     * @memberof JobEndPatchResponseDataJob
     */
    'employmentCondition'?: JobEndPatchResponseDataJobEmploymentCondition;
    /**
     * 
     * @type {JobEndPatchResponseDataJobRemunerationSchedule}
     * @memberof JobEndPatchResponseDataJob
     */
    'remunerationSchedule'?: JobEndPatchResponseDataJobRemunerationSchedule;
    /**
     * The name of this [Job](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof JobEndPatchResponseDataJob
     */
    'name'?: string;
    /**
     * 
     * @type {JobEndPatchResponseDataJobPositionTitle}
     * @memberof JobEndPatchResponseDataJob
     */
    'positionTitle'?: JobEndPatchResponseDataJobPositionTitle;
    /**
     * 
     * @type {JobEndPatchResponseDataJobFte}
     * @memberof JobEndPatchResponseDataJob
     */
    'fte'?: JobEndPatchResponseDataJobFte;
    /**
     * An array of comment objects that annotate the reason for [Job](https://developers.intellihr.io/docs/v1/) changes. Will be an empty array when there has been no updates to the Job.
     * @type {Array<JobEndPatchResponseDataJobCommentsInner>}
     * @memberof JobEndPatchResponseDataJob
     */
    'comments'?: Array<JobEndPatchResponseDataJobCommentsInner>;
    /**
     * 
     * @type {JobEndPatchResponseDataJobLastestJobChangeComment}
     * @memberof JobEndPatchResponseDataJob
     */
    'lastestJobChangeComment'?: JobEndPatchResponseDataJobLastestJobChangeComment;
    /**
     * The [Work Class](https://developers.intellihr.io/docs/v1/) of this [Job](https://developers.intellihr.io/docs/v1/). This is extra details about the [Work Type](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof JobEndPatchResponseDataJob
     */
    'workClass'?: string;
    /**
     * This is the [Work Classification](https://developers.intellihr.io/docs/v1/) for this [Job](https://developers.intellihr.io/docs/v1/), it is used to differentiate between full-time and part time employees vs unpaid volunteers. Enum: `Permanent`, `Fixed Contract`, `Unpaid`, `Temporary/Casual`, `Independent Contract`.
     * @type {string}
     * @memberof JobEndPatchResponseDataJob
     */
    'workType'?: string;
    /**
     * Whether this job is the primary job on the [Person](https://developers.intellihr.io/docs/v1/). Only one job on a [Person](https://developers.intellihr.io/docs/v1/) can be primary at a time.
     * @type {boolean}
     * @memberof JobEndPatchResponseDataJob
     */
    'isPrimaryJob'?: boolean;
    /**
     * The current status of this job within this organisation. Enum: `Past Job`, `Future Job`, `Ending Job`, `Current Job`.
     * @type {string}
     * @memberof JobEndPatchResponseDataJob
     */
    'jobStatus'?: string;
    /**
     * 
     * @type {JobEndPatchResponseDataJobCreatedBy}
     * @memberof JobEndPatchResponseDataJob
     */
    'createdBy'?: JobEndPatchResponseDataJobCreatedBy;
    /**
     * 
     * @type {JobEndPatchResponseDataJobUpdatedBy}
     * @memberof JobEndPatchResponseDataJob
     */
    'updatedBy'?: JobEndPatchResponseDataJobUpdatedBy;
    /**
     * The start date of the current position the person is in. The gap between the `companyStartDate` and `positionStartDate` will be filled with \"Previous position title\" historical records, to correctly depict the person as having no information recorded for old job positions. This date will follow the format defined by [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6).   YYYY-MM-DD date formatting is also supported, although by using this format the date will be stored as the start of day in UTC time, not the requesting tenants timezone.
     * @type {string}
     * @memberof JobEndPatchResponseDataJob
     */
    'positionStartDate'?: string;
    /**
     * The date this [Job](https://developers.intellihr.io/docs/v1/) started or will start within the organisation. This date will follow the format defined by [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6).
     * @type {string}
     * @memberof JobEndPatchResponseDataJob
     */
    'companyStartDate'?: string;
    /**
     * 
     * @type {RFC3339DatetimeProperty3}
     * @memberof JobEndPatchResponseDataJob
     */
    'companyEndDate'?: RFC3339DatetimeProperty3;
    /**
     * Whether the end date has been finalised within the intelliHR application.
     * @type {boolean}
     * @memberof JobEndPatchResponseDataJob
     */
    'isEndDateConfirmed'?: boolean;
    /**
     * 
     * @type {JobEndPatchResponseDataJobTurnoverType}
     * @memberof JobEndPatchResponseDataJob
     */
    'turnoverType'?: JobEndPatchResponseDataJobTurnoverType;
    /**
     * 
     * @type {JobEndPatchResponseDataJobTurnoverReason}
     * @memberof JobEndPatchResponseDataJob
     */
    'turnoverReason'?: JobEndPatchResponseDataJobTurnoverReason;
    /**
     * The custom field values for this Job
     * @type {CustomFieldsResponse}
     * @memberof JobEndPatchResponseDataJob
     */
    'customFields'?: CustomFieldsResponse;
    /**
     * When this record was created. This date will follow the format defined by [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6).
     * @type {string}
     * @memberof JobEndPatchResponseDataJob
     */
    'createdAt'?: string;
}

