/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmploymentConditionPropertyAwardName } from './employment-condition-property-award-name';
import { JobProperty2EmploymentConditionOneOf } from './job-property2-employment-condition-one-of';

/**
 * @type JobProperty2EmploymentCondition
 * An instance of the [Employment Condition](https://developers.intellihr.io/docs/v1/) that is attached to the job, contains the dates it is effective for.
 * @export
 */
export type JobProperty2EmploymentCondition = JobProperty2EmploymentConditionOneOf | Null;


