/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobCreateRequestRecruitmentSource } from './job-create-request-recruitment-source';

/**
 * The recruitment details for this [Job](https://developers.intellihr.io/docs/v1/).
 * @export
 * @interface JobCreateRequestRecruitment
 */
export interface JobCreateRequestRecruitment {
    /**
     * 
     * @type {JobCreateRequestRecruitmentSource}
     * @memberof JobCreateRequestRecruitment
     */
    'source'?: JobCreateRequestRecruitmentSource;
    /**
     * The cost of the recruitment. Any number exceeding 8 decimal places will be rounded up.
     * @type {number}
     * @memberof JobCreateRequestRecruitment
     */
    'cost'?: number;
    /**
     * The currency used to recruit this [Job](https://developers.intellihr.io/docs/v1/). An international currency code. Typically AUD for Australian dollar, USD for American dollar etc. See [Official list of codes](https://www.iban.com/currency-codes).
     * @type {string}
     * @memberof JobCreateRequestRecruitment
     */
    'currency'?: string;
}

