/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The default remuneration component this addition is based on. This is specified as a search object, which will match the remuneration component which best fits the keys for this object. Multiple keys can be used together to further narrow search results.
 * @export
 * @interface JobCreateRequestRemunerationScheduleAdditionsInnerDefaultRemunerationComponent
 */
export interface JobCreateRequestRemunerationScheduleAdditionsInnerDefaultRemunerationComponent {
    /**
     * The identifier string for the default remuneration component.
     * @type {string}
     * @memberof JobCreateRequestRemunerationScheduleAdditionsInnerDefaultRemunerationComponent
     */
    'id'?: string;
    /**
     * Name of the default remuneration component.
     * @type {string}
     * @memberof JobCreateRequestRemunerationScheduleAdditionsInnerDefaultRemunerationComponent
     */
    'name'?: string;
}

