/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobEndRemoveResponseDataJobExtendedLeaveOneOf } from './job-end-remove-response-data-job-extended-leave-one-of';
import { JobEndRemoveResponseDataJobExtendedLeaveOneOfType } from './job-end-remove-response-data-job-extended-leave-one-of-type';

/**
 * @type JobEndRemoveResponseDataJobExtendedLeave
 * If this job has active extended leave, this will be populated, otherwise it will be null
 * @export
 */
export type JobEndRemoveResponseDataJobExtendedLeave = JobEndRemoveResponseDataJobExtendedLeaveOneOf | Null;


