/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobTimelineEventExtendedLeaveEndedOneOf } from './job-timeline-event-extended-leave-ended-one-of';
import { JobTimelineEventExtendedLeaveEndedOneOfLeaveType } from './job-timeline-event-extended-leave-ended-one-of-leave-type';

/**
 * @type JobTimelineEventExtendedLeaveEnded
 * @export
 */
export type JobTimelineEventExtendedLeaveEnded = JobTimelineEventExtendedLeaveEndedOneOf | Null;


