/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobCreateRequestRemunerationScheduleBreakdownsInnerDefaultRemunerationComponent } from './job-create-request-remuneration-schedule-breakdowns-inner-default-remuneration-component';

/**
 * 
 * @export
 * @interface JobCreateRequestRemunerationScheduleBreakdownsInner
 */
export interface JobCreateRequestRemunerationScheduleBreakdownsInner {
    /**
     * The name of this Breakdowns.
     * @type {string}
     * @memberof JobCreateRequestRemunerationScheduleBreakdownsInner
     */
    'name': string;
    /**
     * How this breakdown is calculated and applied to the base amount, MultipleOfBase is multiplied by baseAnnualSalary and then added to the total while FixedAmount is added directly to the total. Enum: `MultipleOfBase`, `FixedAmount`.
     * @type {string}
     * @memberof JobCreateRequestRemunerationScheduleBreakdownsInner
     */
    'type': string;
    /**
     * For MultipleOfBase this is the multiplier (e.g. 9 = 9%) while for fixed amount this is the amount to directly add to the total.
     * @type {string}
     * @memberof JobCreateRequestRemunerationScheduleBreakdownsInner
     */
    'value': string;
    /**
     * The currency used for this breakdown. An international currency code. Typically AUD for Australian dollar, USD for American dollar etc. See [Official list of codes](https://www.iban.com/currency-codes).
     * @type {string}
     * @memberof JobCreateRequestRemunerationScheduleBreakdownsInner
     */
    'currency'?: string;
    /**
     * 
     * @type {JobCreateRequestRemunerationScheduleBreakdownsInnerDefaultRemunerationComponent}
     * @memberof JobCreateRequestRemunerationScheduleBreakdownsInner
     */
    'defaultRemunerationComponent'?: JobCreateRequestRemunerationScheduleBreakdownsInnerDefaultRemunerationComponent;
}

