/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LocationsCreateRequestCustomFieldsValue } from './locations-create-request-custom-fields-value';
import { UUIDv4Property3 } from './uuidv4-property3';

/**
 * 
 * @export
 * @interface LocationsCreateRequest
 */
export interface LocationsCreateRequest {
    /**
     * 
     * @type {UUIDv4Property3}
     * @memberof LocationsCreateRequest
     */
    'parentId'?: UUIDv4Property3;
    /**
     * Name given to this [Location](https://developers.intellihr.io/docs/v1/). This name would normally be shown to users of the system.
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'name': string;
    /**
     * Code given to this [Location](https://developers.intellihr.io/docs/v1/)
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'code'?: string;
    /**
     * The address of this location.
     * @type {string}
     * @memberof LocationsCreateRequest
     */
    'address'?: string;
    /**
     * Specifies whether users can select this [Location](https://developers.intellihr.io/docs/v1/) in dropdowns.
     * @type {boolean}
     * @memberof LocationsCreateRequest
     */
    'isEnabled'?: boolean;
    /**
     * The custom field values for this Location
     * @type {{ [key: string]: LocationsCreateRequestCustomFieldsValue; }}
     * @memberof LocationsCreateRequest
     */
    'customFields'?: { [key: string]: LocationsCreateRequestCustomFieldsValue; };
}

