/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LocationsPatchRequestCustomFieldsValueValueAnyOfInnerJob } from './locations-patch-request-custom-fields-value-value-any-of-inner-job';
import { LocationsPatchRequestCustomFieldsValueValueAnyOfInnerPerson } from './locations-patch-request-custom-fields-value-value-any-of-inner-person';

/**
 * 
 * @export
 * @interface LocationsPatchRequestCustomFieldsValueValueAnyOfInner
 */
export interface LocationsPatchRequestCustomFieldsValueValueAnyOfInner {
    /**
     * 
     * @type {LocationsPatchRequestCustomFieldsValueValueAnyOfInnerPerson}
     * @memberof LocationsPatchRequestCustomFieldsValueValueAnyOfInner
     */
    'person'?: LocationsPatchRequestCustomFieldsValueValueAnyOfInnerPerson;
    /**
     * 
     * @type {LocationsPatchRequestCustomFieldsValueValueAnyOfInnerJob}
     * @memberof LocationsPatchRequestCustomFieldsValueValueAnyOfInner
     */
    'job'?: LocationsPatchRequestCustomFieldsValueValueAnyOfInnerJob;
}

