/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PayGradeCurrency4
 */
export interface PayGradeCurrency4 {
    /**
     * Administrative, short code associated to the Currency.
     * @type {string}
     * @memberof PayGradeCurrency4
     */
    'code'?: string;
    /**
     * User friendly name given to the Currency.
     * @type {string}
     * @memberof PayGradeCurrency4
     */
    'name'?: string;
}

