/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayGrade } from './pay-grade';
import { PayGradesListLinks } from './pay-grades-list-links';
import { PayGradesListMeta } from './pay-grades-list-meta';

/**
 * 
 * @export
 * @interface PayGradesList
 */
export interface PayGradesList {
    /**
     * 
     * @type {Array<PayGrade>}
     * @memberof PayGradesList
     */
    'data'?: Array<PayGrade>;
    /**
     * 
     * @type {PayGradesListMeta}
     * @memberof PayGradesList
     */
    'meta'?: PayGradesListMeta;
    /**
     * 
     * @type {PayGradesListLinks}
     * @memberof PayGradesList
     */
    'links'?: PayGradesListLinks;
}

