/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayGradeChangeUser } from './pay-grade-change-user';

/**
 * @type PayGradePropertyChangeUser
 * The [User](https://developers.intellihr.io/docs/v1/) who last changed this [Pay Grade](https://developers.intellihr.io/docs/v1/)
 * @export
 */
export type PayGradePropertyChangeUser = Null | PayGradeChangeUser;


