/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PeopleUpdateRequestPhoneNumbersInnerCustomFieldsValue } from './people-update-request-phone-numbers-inner-custom-fields-value';

/**
 * 
 * @export
 * @interface PeopleUpdateRequestPhoneNumbersInner
 */
export interface PeopleUpdateRequestPhoneNumbersInner {
    /**
     * The phone number. This number can be prefixed with an area code. When this happens, the system will automatically try to determine the origin country for the phone number
     * @type {string}
     * @memberof PeopleUpdateRequestPhoneNumbersInner
     */
    'number'?: string;
    /**
     * Denotes whether this phone is personal or a work phone number.
     * @type {boolean}
     * @memberof PeopleUpdateRequestPhoneNumbersInner
     */
    'isPersonal'?: boolean;
    /**
     * Denotes whether this phone is the primary contact phone number.
     * @type {boolean}
     * @memberof PeopleUpdateRequestPhoneNumbersInner
     */
    'isPrimary'?: boolean;
    /**
     * The custom field values for this phone number
     * @type {{ [key: string]: PeopleUpdateRequestPhoneNumbersInnerCustomFieldsValue; }}
     * @memberof PeopleUpdateRequestPhoneNumbersInner
     */
    'customFields'?: { [key: string]: PeopleUpdateRequestPhoneNumbersInnerCustomFieldsValue; };
}

