/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PeopleDocumentsPatchResponseData } from './people-documents-patch-response-data';
import { PeopleDocumentsPatchResponseMeta } from './people-documents-patch-response-meta';

/**
 * 
 * @export
 * @interface PeopleDocumentsPatchResponse
 */
export interface PeopleDocumentsPatchResponse {
    /**
     * 
     * @type {PeopleDocumentsPatchResponseData}
     * @memberof PeopleDocumentsPatchResponse
     */
    'data'?: PeopleDocumentsPatchResponseData;
    /**
     * 
     * @type {PeopleDocumentsPatchResponseMeta}
     * @memberof PeopleDocumentsPatchResponse
     */
    'meta'?: PeopleDocumentsPatchResponseMeta;
}

