/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PeopleDataUserAccountOneOf } from './people-data-user-account-one-of';
import { PeopleDataUserAccountOneOfUserPermissionGroupsInner } from './people-data-user-account-one-of-user-permission-groups-inner';

/**
 * @type PeopleDataUserAccount
 * Details about this [Person\'s](https://developers.intellihr.io/docs/v1/) linked user account. Including this object will create a user account linked to this person, allowing them to login to the platform. If excluded the person will be created without an accompanying user account.
 * @export
 */
export type PeopleDataUserAccount = Null | PeopleDataUserAccountOneOf;


