/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PermissionGroup } from './permission-group';
import { PermissionGroupsListLinks } from './permission-groups-list-links';
import { PermissionGroupsListMeta } from './permission-groups-list-meta';

/**
 * 
 * @export
 * @interface PermissionGroupsList
 */
export interface PermissionGroupsList {
    /**
     * 
     * @type {Array<PermissionGroup>}
     * @memberof PermissionGroupsList
     */
    'data'?: Array<PermissionGroup>;
    /**
     * 
     * @type {PermissionGroupsListMeta}
     * @memberof PermissionGroupsList
     */
    'meta'?: PermissionGroupsListMeta;
    /**
     * 
     * @type {PermissionGroupsListLinks}
     * @memberof PermissionGroupsList
     */
    'links'?: PermissionGroupsListLinks;
}

