/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PersonDocumentsPatchRequest
 */
export interface PersonDocumentsPatchRequest {
    /**
     * The identifier string for the [Person](https://developers.intellihr.io/docs/v1/) to whom this [Document](https://developers.intellihr.io/docs/v1/) belongs.
     * @type {string}
     * @memberof PersonDocumentsPatchRequest
     */
    'personId': string;
    /**
     * The filename of the document. This will be used for display name. Includes extension.
     * @type {string}
     * @memberof PersonDocumentsPatchRequest
     */
    'filename'?: string;
    /**
     * The upload status of this [Document](https://developers.intellihr.io/docs/v1/). Enum: `SUCCESS`, `PENDING`, `FAILED`.
     * @type {any}
     * @memberof PersonDocumentsPatchRequest
     */
    'uploadStatus'?: any;
}

