/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { QualificationLibraryItemExpiryPeriods } from './qualification-library-item-expiry-periods';
import { QualificationLibraryItemQualificationType } from './qualification-library-item-qualification-type';

/**
 * 
 * @export
 * @interface QualificationLibraryItem
 */
export interface QualificationLibraryItem {
    /**
     * The identifier string for the [Qualification Library Item](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof QualificationLibraryItem
     */
    'id'?: string;
    /**
     * The name of this [Qualification Library Item](https://developers.intellihr.io/docs/v1/)
     * @type {string}
     * @memberof QualificationLibraryItem
     */
    'name'?: string;
    /**
     * 
     * @type {QualificationLibraryItemQualificationType}
     * @memberof QualificationLibraryItem
     */
    'qualificationType'?: QualificationLibraryItemQualificationType;
    /**
     * The expiry type for this library item
     * @type {string}
     * @memberof QualificationLibraryItem
     */
    'qualificationExpiryType'?: QualificationLibraryItemQualificationExpiryTypeEnum;
    /**
     * The expiry type for this library item
     * @type {string}
     * @memberof QualificationLibraryItem
     */
    'qualificationRegistrationNumberVisibilityType'?: QualificationLibraryItemQualificationRegistrationNumberVisibilityTypeEnum;
    /**
     * If documents are required for this library item
     * @type {string}
     * @memberof QualificationLibraryItem
     */
    'qualificationAttachmentRequirementType'?: QualificationLibraryItemQualificationAttachmentRequirementTypeEnum;
    /**
     * Period in days, that there is a warning before the expiry of the qualification. If qualificationExpiryType is set to EXPIRY_INAPPLICABLE, this value will be ignored.
     * @type {number}
     * @memberof QualificationLibraryItem
     */
    'expiryWarningPeriod'?: number;
    /**
     * 
     * @type {QualificationLibraryItemExpiryPeriods}
     * @memberof QualificationLibraryItem
     * @deprecated
     */
    'expiryPeriods'?: QualificationLibraryItemExpiryPeriods;
    /**
     * If this [Qualification Library Item](https://developers.intellihr.io/docs/v1/) will send expiry warning/s using the periods defined. If qualificationExpiryType is set to EXPIRY_INAPPLICABLE, this value will be ignored.
     * @type {boolean}
     * @memberof QualificationLibraryItem
     */
    'sendExpiryWarning'?: boolean;
    /**
     * Number of qualification instances currently being used with this qualification library item
     * @type {number}
     * @memberof QualificationLibraryItem
     */
    'qualificationInstanceUsageCount'?: number;
    /**
     * Number of job requirement groups currently being used with this qualification library item
     * @type {number}
     * @memberof QualificationLibraryItem
     */
    'jobRequirementGroupUsageCount'?: number;
    /**
     * Number of job requirements currently being used with this qualification library item
     * @type {number}
     * @memberof QualificationLibraryItem
     */
    'jobRequirementUsageCount'?: number;
}

type QualificationLibraryItemQualificationExpiryTypeEnum = 'EXPIRY_INAPPLICABLE' | 'EXPIRY_OPTIONAL' | 'EXPIRY_REQUIRED'
type QualificationLibraryItemQualificationRegistrationNumberVisibilityTypeEnum = 'REGISTRATION_NUMBER_INAPPLICABLE' | 'REGISTRATION_NUMBER_OPTIONAL' | 'REGISTRATION_NUMBER_REQUIRED'
type QualificationLibraryItemQualificationAttachmentRequirementTypeEnum = 'DOCUMENTS_OPTIONAL' | 'DOCUMENTS_REQUIRED'


