/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { QualificationInstance } from './qualification-instance';
import { QualificationsListLinks } from './qualifications-list-links';
import { QualificationsListMeta } from './qualifications-list-meta';

/**
 * 
 * @export
 * @interface QualificationsList
 */
export interface QualificationsList {
    /**
     * 
     * @type {Array<QualificationInstance>}
     * @memberof QualificationsList
     */
    'data'?: Array<QualificationInstance>;
    /**
     * 
     * @type {QualificationsListMeta}
     * @memberof QualificationsList
     */
    'meta'?: QualificationsListMeta;
    /**
     * 
     * @type {QualificationsListLinks}
     * @memberof QualificationsList
     */
    'links'?: QualificationsListLinks;
}

