/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { QualificationInstancePropertyLibraryItem } from './qualification-instance-property-library-item';
import { QualificationInstancePropertyPerson } from './qualification-instance-property-person';
import { QualificationInstancePropertyQualificationStatus } from './qualification-instance-property-qualification-status';
import { QualificationInstancesCreateRequestIssuingOrganisation } from './qualification-instances-create-request-issuing-organisation';
import { QualificationInstancesCreateRequestNotes } from './qualification-instances-create-request-notes';
import { QualificationInstancesCreateRequestRegistrationNumber } from './qualification-instances-create-request-registration-number';
import { RFC3339DatetimeProperty10 } from './rfc3339-datetime-property10';
import { RFC3339DatetimeProperty11 } from './rfc3339-datetime-property11';
import { RFC3339DatetimeProperty9 } from './rfc3339-datetime-property9';

/**
 * 
 * @export
 * @interface QualificationInstanceProperty
 */
export interface QualificationInstanceProperty {
    /**
     * The identifier string for the [Qualification Instance](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof QualificationInstanceProperty
     */
    'id'?: string;
    /**
     * 
     * @type {RFC3339DatetimeProperty10}
     * @memberof QualificationInstanceProperty
     */
    'expiryDate'?: RFC3339DatetimeProperty10;
    /**
     * 
     * @type {RFC3339DatetimeProperty11}
     * @memberof QualificationInstanceProperty
     */
    'expiryNotificationQueuedAt'?: RFC3339DatetimeProperty11;
    /**
     * 
     * @type {RFC3339DatetimeProperty9}
     * @memberof QualificationInstanceProperty
     */
    'issueDate'?: RFC3339DatetimeProperty9;
    /**
     * 
     * @type {QualificationInstancesCreateRequestIssuingOrganisation}
     * @memberof QualificationInstanceProperty
     */
    'issuingOrganisation'?: QualificationInstancesCreateRequestIssuingOrganisation;
    /**
     * 
     * @type {QualificationInstancesCreateRequestNotes}
     * @memberof QualificationInstanceProperty
     */
    'notes'?: QualificationInstancesCreateRequestNotes;
    /**
     * 
     * @type {QualificationInstancePropertyPerson}
     * @memberof QualificationInstanceProperty
     */
    'person'?: QualificationInstancePropertyPerson;
    /**
     * 
     * @type {QualificationInstancePropertyQualificationStatus}
     * @memberof QualificationInstanceProperty
     * @deprecated
     */
    'qualificationStatus'?: QualificationInstancePropertyQualificationStatus;
    /**
     * The status of this [Qualification Instance](https://developers.intellihr.io/docs/v1/)
     * @type {string}
     * @memberof QualificationInstanceProperty
     */
    'status'?: QualificationInstancePropertyStatusEnum;
    /**
     * 
     * @type {QualificationInstancePropertyLibraryItem}
     * @memberof QualificationInstanceProperty
     */
    'libraryItem'?: QualificationInstancePropertyLibraryItem;
    /**
     * 
     * @type {QualificationInstancesCreateRequestRegistrationNumber}
     * @memberof QualificationInstanceProperty
     */
    'registrationNumber'?: QualificationInstancesCreateRequestRegistrationNumber;
}

type QualificationInstancePropertyStatusEnum = 'DRAFT' | 'AWAITING_APPROVAL' | 'DECLINED' | 'APPROVED' | 'REVOKED' | 'EXPIRED' | 'EXPIRING_SOON' | 'CURRENT' | 'FUTURE' | 'RENEWING' | 'NON_COMPLIANT'


