/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExtendedLeavePropertyPersonEmployeeNumber } from './extended-leave-property-person-employee-number';

/**
 * The subject [Person](https://developers.intellihr.io/docs/v1/) of this [Qualification Instance](https://developers.intellihr.io/docs/v1/)
 * @export
 * @interface QualificationInstancePerson
 */
export interface QualificationInstancePerson {
    /**
     * The identifier string for the [Person](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof QualificationInstancePerson
     */
    'id'?: string;
    /**
     * Name to display throughout the system for this [Person](https://developers.intellihr.io/docs/v1/). Generally follows the pattern preferredName (firstName) lastName, but can be configured on a tenant-wide basis to be a different format.
     * @type {string}
     * @memberof QualificationInstancePerson
     */
    'displayName'?: string;
    /**
     * 
     * @type {ExtendedLeavePropertyPersonEmployeeNumber}
     * @memberof QualificationInstancePerson
     */
    'employeeNumber'?: ExtendedLeavePropertyPersonEmployeeNumber;
    /**
     * An autogenerated number that uniquely identifies a [Person](https://developers.intellihr.io/docs/v1/) in intelliHR. It may be hidden in the system\'s UI depending upon your tenant\'s configuration.
     * @type {number}
     * @memberof QualificationInstancePerson
     */
    'autoIncrementIntellihrId'?: number;
    /**
     * Link on the public api to get more information on this piece of data.
     * @type {string}
     * @memberof QualificationInstancePerson
     */
    'link'?: string;
}

