/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { QualificationLibraryItem } from './qualification-library-item';
import { QualificationLibraryItemsListLinks } from './qualification-library-items-list-links';
import { QualificationLibraryItemsListMeta } from './qualification-library-items-list-meta';

/**
 * 
 * @export
 * @interface QualificationLibraryItemsList
 */
export interface QualificationLibraryItemsList {
    /**
     * 
     * @type {Array<QualificationLibraryItem>}
     * @memberof QualificationLibraryItemsList
     */
    'data'?: Array<QualificationLibraryItem>;
    /**
     * 
     * @type {QualificationLibraryItemsListMeta}
     * @memberof QualificationLibraryItemsList
     */
    'meta'?: QualificationLibraryItemsListMeta;
    /**
     * 
     * @type {QualificationLibraryItemsListLinks}
     * @memberof QualificationLibraryItemsList
     */
    'links'?: QualificationLibraryItemsListLinks;
}

