/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface QualificationStatusProperty
 */
export interface QualificationStatusProperty {
    /**
     * The identifier string for the [Qualification Status](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof QualificationStatusProperty
     */
    'id'?: string;
    /**
     * The name of this [Qualification Status](https://developers.intellihr.io/docs/v1/)
     * @type {string}
     * @memberof QualificationStatusProperty
     */
    'name'?: string;
}

