/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The type of qualification this [Qualification Library Item](https://developers.intellihr.io/docs/v1/) is for
 * @export
 * @interface QualificationInstanceLibraryItemQualificationType
 */
export interface QualificationInstanceLibraryItemQualificationType {
    /**
     * The identifier string for the Qualification Type.
     * @type {string}
     * @memberof QualificationInstanceLibraryItemQualificationType
     */
    'id'?: string;
    /**
     * Library Item name
     * @type {string}
     * @memberof QualificationInstanceLibraryItemQualificationType
     */
    'name'?: string;
}

