/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UUIDv4Property4 } from './uuidv4-property4';

/**
 * 
 * @export
 * @interface RecruitmentSourceProperty
 */
export interface RecruitmentSourceProperty {
    /**
     * The identifier string for the [Recruitment Source](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof RecruitmentSourceProperty
     */
    'id'?: string;
    /**
     * The name given to this recruitment source.
     * @type {string}
     * @memberof RecruitmentSourceProperty
     */
    'name'?: string;
    /**
     * 
     * @type {UUIDv4Property4}
     * @memberof RecruitmentSourceProperty
     */
    'parentId'?: UUIDv4Property4;
    /**
     * Specifies whether users can select this [Recruitment Source](https://developers.intellihr.io/docs/v1/) in dropdowns.
     * @type {boolean}
     * @memberof RecruitmentSourceProperty
     */
    'isEnabled'?: boolean;
}

