/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RepresentativeTypeProperty
 */
export interface RepresentativeTypeProperty {
    /**
     * The identifier string for the [Representative Type](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof RepresentativeTypeProperty
     */
    'id'?: string;
    /**
     * Name of this [Representative Type](https://developers.intellihr.io/docs/v1/)
     * @type {string}
     * @memberof RepresentativeTypeProperty
     */
    'name'?: string;
    /**
     * Type of Object this [Representative Type](https://developers.intellihr.io/docs/v1/) relates to.
     * @type {string}
     * @memberof RepresentativeTypeProperty
     */
    'modelType'?: RepresentativeTypePropertyModelTypeEnum;
}

type RepresentativeTypePropertyModelTypeEnum = 'BUSINESS_UNIT' | 'LOCATION'


