/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SkillDisciplineSchemaSkillsInner } from './skill-discipline-schema-skills-inner';

/**
 * 
 * @export
 * @interface SkillDisciplineSchema
 */
export interface SkillDisciplineSchema {
    /**
     * The identifier string for the [Skill Discipline](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof SkillDisciplineSchema
     */
    'id'?: string;
    /**
     * The name of this [Skill Discipline](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof SkillDisciplineSchema
     */
    'name'?: string;
    /**
     * An array of Skills belonging to this Skill Discipline.
     * @type {Array<SkillDisciplineSchemaSkillsInner>}
     * @memberof SkillDisciplineSchema
     */
    'skills'?: Array<SkillDisciplineSchemaSkillsInner>;
}

