/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SkillDisciplineSchema } from './skill-discipline-schema';
import { SkillDisciplinesListLinks } from './skill-disciplines-list-links';
import { SkillDisciplinesListMeta } from './skill-disciplines-list-meta';

/**
 * 
 * @export
 * @interface SkillDisciplinesList
 */
export interface SkillDisciplinesList {
    /**
     * 
     * @type {Array<SkillDisciplineSchema>}
     * @memberof SkillDisciplinesList
     */
    'data'?: Array<SkillDisciplineSchema>;
    /**
     * 
     * @type {SkillDisciplinesListMeta}
     * @memberof SkillDisciplinesList
     */
    'meta'?: SkillDisciplinesListMeta;
    /**
     * 
     * @type {SkillDisciplinesListLinks}
     * @memberof SkillDisciplinesList
     */
    'links'?: SkillDisciplinesListLinks;
}

