/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SkillDisciplineSchemaSkillsInner
 */
export interface SkillDisciplineSchemaSkillsInner {
    /**
     * The identifier string for the [Skills](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof SkillDisciplineSchemaSkillsInner
     */
    'id'?: string;
    /**
     * The name/position title of this [Skills](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof SkillDisciplineSchemaSkillsInner
     */
    'name'?: string;
    /**
     * Link on the public api to get more information on this piece of data.
     * @type {string}
     * @memberof SkillDisciplineSchemaSkillsInner
     */
    'link'?: string;
}

