/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SkillsGetAllFiltersParameter
 */
export interface SkillsGetAllFiltersParameter {
    /**
     * Whether this [Skill](https://developers.intellihr.io/docs/v1/) is business critical.  Example filter: `filters[isBusinessCritical][eq]=true`  This filter supports the equality `[eq]` operation
     * @type {boolean}
     * @memberof SkillsGetAllFiltersParameter
     */
    'isBusinessCritical'?: boolean;
    /**
     * The identifier string for the [Skill Discipline](https://developers.intellihr.io/docs/v1/) to which this [Skill](https://developers.intellihr.io/docs/v1/) belongs.  Example filter: `filters[skillDisciplineId][eq]=8a5f3ea6-ea6b-4425-8a87-3c256bb7b6f9`  This filter supports the equality `[eq]` operation
     * @type {string}
     * @memberof SkillsGetAllFiltersParameter
     */
    'skillDisciplineId'?: string;
}

