/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * This field is `required` when type `PEOPLE_DROPDOWN` is used
 * @export
 * @interface ThePeopleDropdownDefinitionOfTheCustomFieldDefinitionProperty
 */
export interface ThePeopleDropdownDefinitionOfTheCustomFieldDefinitionProperty {
    /**
     * Optionally include jobs as custom field
     * @type {boolean}
     * @memberof ThePeopleDropdownDefinitionOfTheCustomFieldDefinitionProperty
     */
    'allowSelectingIndividualJobs'?: boolean;
}

