/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OptionsPropertyInner } from './options-property-inner';

/**
 * This field is becomes `required` with type `MULTI_SELECT` or `SINGLE_SELECT`
 * @export
 * @interface TheSelectDefinitionOfTheCustomFieldDefinitionProperty
 */
export interface TheSelectDefinitionOfTheCustomFieldDefinitionProperty {
    /**
     * List of options
     * @type {Array<OptionsPropertyInner>}
     * @memberof TheSelectDefinitionOfTheCustomFieldDefinitionProperty
     */
    'options'?: Array<OptionsPropertyInner>;
}

