/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TrainingsPatchRequestCustomFieldsValueValueAnyOfInnerJob } from './trainings-patch-request-custom-fields-value-value-any-of-inner-job';
import { TrainingsPatchRequestCustomFieldsValueValueAnyOfInnerPerson } from './trainings-patch-request-custom-fields-value-value-any-of-inner-person';

/**
 * 
 * @export
 * @interface TrainingsPatchRequestCustomFieldsValueValueAnyOfInner
 */
export interface TrainingsPatchRequestCustomFieldsValueValueAnyOfInner {
    /**
     * 
     * @type {TrainingsPatchRequestCustomFieldsValueValueAnyOfInnerPerson}
     * @memberof TrainingsPatchRequestCustomFieldsValueValueAnyOfInner
     */
    'person'?: TrainingsPatchRequestCustomFieldsValueValueAnyOfInnerPerson;
    /**
     * 
     * @type {TrainingsPatchRequestCustomFieldsValueValueAnyOfInnerJob}
     * @memberof TrainingsPatchRequestCustomFieldsValueValueAnyOfInner
     */
    'job'?: TrainingsPatchRequestCustomFieldsValueValueAnyOfInnerJob;
}

