/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TrainingProperty } from './training-property';
import { TrainingsMeta } from './trainings-meta';

/**
 * 
 * @export
 * @interface Trainings
 */
export interface Trainings {
    /**
     * 
     * @type {TrainingProperty}
     * @memberof Trainings
     */
    'data'?: TrainingProperty;
    /**
     * 
     * @type {TrainingsMeta}
     * @memberof Trainings
     */
    'meta'?: TrainingsMeta;
}

