/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TrainingStatuses
 */
export interface TrainingStatuses {
    /**
     * The identifier string for the [Training Statuses](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof TrainingStatuses
     */
    'id'?: string;
    /**
     * The name given to describe the status of [Training](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof TrainingStatuses
     */
    'name'?: string;
}

