/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The search object for [Training Statuses](https://developers.intellihr.io/docs/v1/) of the [Training](https://developers.intellihr.io/docs/v1/). Defaults to `Enrolled` if undefined
 * @export
 * @interface TrainingsCreateRequestStatus
 */
export interface TrainingsCreateRequestStatus {
    /**
     * The identifier string for the [Training Statuses](https://developers.intellihr.io/docs/v1/) of the [Training](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof TrainingsCreateRequestStatus
     */
    'id'?: string;
    /**
     * User friendly name given to the [Training Statuses](https://developers.intellihr.io/docs/v1/) of the [Training](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof TrainingsCreateRequestStatus
     */
    'name'?: string;
}

