/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RFC3339DatetimeProperty12 } from './rfc3339-datetime-property12';

/**
 * The [Job](https://developers.intellihr.io/docs/v1/) of the [Person](https://developers.intellihr.io/docs/v1/) who did the [Training](https://developers.intellihr.io/docs/v1/).
 * @export
 * @interface TrainingJob
 */
export interface TrainingJob {
    /**
     * The identifier string for the [Job](https://developers.intellihr.io/docs/v1/) of the [Training](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof TrainingJob
     */
    'id'?: string;
    /**
     * The name of the [Persons](https://developers.intellihr.io/docs/v1/) [Job](https://developers.intellihr.io/docs/v1/) who did the [Training](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof TrainingJob
     */
    'name'?: string;
    /**
     * The [Jobs](https://developers.intellihr.io/docs/v1/) effective start date. This date will follow the format defined by [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6).
     * @type {string}
     * @memberof TrainingJob
     */
    'startDate'?: string;
    /**
     * 
     * @type {RFC3339DatetimeProperty12}
     * @memberof TrainingJob
     */
    'endDate'?: RFC3339DatetimeProperty12;
    /**
     * The Status Schema. Enum: `Past Job`, `Future Job`, `Ending Job`, `Current Job`.
     * @type {string}
     * @memberof TrainingJob
     */
    'jobStatus'?: string;
    /**
     * Link on the public api to get more information on this piece of data.
     * @type {string}
     * @memberof TrainingJob
     */
    'link'?: string;
}

