/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * [Person](https://developers.intellihr.io/docs/v1/) to whom this [User](https://developers.intellihr.io/docs/v1/) belongs. This [Person](https://developers.intellihr.io/docs/v1/) is specified as a search object, which will match the person who best fits the keys for this object.         Multiple keys can be used together to further narrow search results (for example, if there are multiple people with the same name, email address         can be used as well to limit to a single person. A validation error will be thrown if this search is unable to be narrowed to a single [Person](https://developers.intellihr.io/docs/v1/).
 * @export
 * @interface UsersCreatePerson
 */
export interface UsersCreatePerson {
    /**
     * The identifier string for the [Person](https://developers.intellihr.io/docs/v1/) to locate in the system.
     * @type {string}
     * @memberof UsersCreatePerson
     */
    'id'?: string;
    /**
     * The name of the [Person](https://developers.intellihr.io/docs/v1/) in intelliHR to search for. Note that the search accounts for differences in name order automatically.
     * @type {string}
     * @memberof UsersCreatePerson
     */
    'name'?: string;
    /**
     * The email address flagged as primary for the [Person](https://developers.intellihr.io/docs/v1/) within the system.
     * @type {string}
     * @memberof UsersCreatePerson
     */
    'primaryEmailAddress'?: string;
    /**
     * A manually entered employee number that identifies a [Person](https://developers.intellihr.io/docs/v1/) in intelliHR. It may be hidden in the system\'s UI depending upon your tenant\'s configuration.
     * @type {string}
     * @memberof UsersCreatePerson
     */
    'employeeNumber'?: string;
    /**
     * An autogenerated number that uniquely identifies a [Person](https://developers.intellihr.io/docs/v1/) in intelliHR. It may be hidden in the system\'s UI depending upon your tenant\'s configuration.
     * @type {string}
     * @memberof UsersCreatePerson
     */
    'autoIncrementIntellihrId'?: string;
}

