/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * @type UUIDv4Property
 * The identifier string for the parent [Business Unit](https://developers.intellihr.io/docs/v1/), or null if there is no parent (this is a top level business unit).
 * @export
 */
export type UUIDv4Property = Null | string;


