/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebhookEventBasic } from './webhook-event-basic';
import { WebhookEventPersonBirthdayUpcomingAllOf } from './webhook-event-person-birthday-upcoming-all-of';
import { WebhookEventScheduled } from './webhook-event-scheduled';

/**
 * @type WebhookEventPersonBirthdayUpcoming
 * @export
 */
export type WebhookEventPersonBirthdayUpcoming = WebhookEventBasic & WebhookEventPersonBirthdayUpcomingAllOf & WebhookEventScheduled;


