/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebhookEventFormCompletedAllOf
 */
export interface WebhookEventFormCompletedAllOf {
    /**
     * 
     * @type {any}
     * @memberof WebhookEventFormCompletedAllOf
     */
    'event'?: any;
    /**
     * 
     * @type {object}
     * @memberof WebhookEventFormCompletedAllOf
     */
    'links'?: object;
    /**
     * The identifier string for the Form id.
     * @type {string}
     * @memberof WebhookEventFormCompletedAllOf
     */
    'formDesignId'?: string;
}

