/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WorkflowsPatchRequestWorkflowFormDesignsInnerSendDate } from './workflows-patch-request-workflow-form-designs-inner-send-date';

/**
 * 
 * @export
 * @interface WorkflowsPatchRequestWorkflowFormDesignsInner
 */
export interface WorkflowsPatchRequestWorkflowFormDesignsInner {
    /**
     * The identifier string for the Workflow Form Design.  Note that this is not the id of the Form Design.  The Form Design that you wish to send will be listed under a \'Workflow Form Design\' in the response from [Workflow Events](https://developers.intellihr.io/docs/v1/), it is the id of this Workflow Form Design that is required in this field, not the id of the Form Design itself.
     * @type {string}
     * @memberof WorkflowsPatchRequestWorkflowFormDesignsInner
     */
    'id': string;
    /**
     * 
     * @type {WorkflowsPatchRequestWorkflowFormDesignsInnerSendDate}
     * @memberof WorkflowsPatchRequestWorkflowFormDesignsInner
     */
    'sendDate'?: WorkflowsPatchRequestWorkflowFormDesignsInnerSendDate;
}

