/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The parent [Work Type](https://developers.intellihr.io/docs/v1/) of this [Work Class](https://developers.intellihr.io/docs/v1/).
 * @export
 * @interface WorkClassesSchemaWorkType
 */
export interface WorkClassesSchemaWorkType {
    /**
     * The identifier string for the [Work Type](https://developers.intellihr.io/docs/v1/) of this [Work Class](https://developers.intellihr.io/docs/v1/).
     * @type {string}
     * @memberof WorkClassesSchemaWorkType
     */
    'id'?: string;
    /**
     * The name of the [Work Type](https://developers.intellihr.io/docs/v1/). Enum: `Permanent`, `Fixed Contract`, `Unpaid`, `Temporary/Casual`, `Independent Contract`.
     * @type {string}
     * @memberof WorkClassesSchemaWorkType
     */
    'name'?: string;
    /**
     * Link on the public api to get more information on this piece of data.
     * @type {string}
     * @memberof WorkClassesSchemaWorkType
     */
    'link'?: string;
}

