/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WorkflowsPatchRequestWorkflowFormDesignsInner } from './workflows-patch-request-workflow-form-designs-inner';

/**
 * 
 * @export
 * @interface WorkflowsPatchRequest
 */
export interface WorkflowsPatchRequest {
    /**
     * The identifier string for the [Job](https://developers.intellihr.io/docs/v1/) to trigger this Workflow for.
     * @type {string}
     * @memberof WorkflowsPatchRequest
     */
    'jobId': string;
    /**
     * Information about the Workflow Form Designs within this [Workflow](https://developers.intellihr.io/docs/v1/).
     * @type {Array<WorkflowsPatchRequestWorkflowFormDesignsInner>}
     * @memberof WorkflowsPatchRequest
     */
    'workflowFormDesigns': Array<WorkflowsPatchRequestWorkflowFormDesignsInner>;
}

