/*
intelliHR Public API

You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

The version of the OpenAPI document: V1
Contact: support@intellihr.co

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WorkTypeProperty } from './work-type-property';
import { WorkTypesMeta } from './work-types-meta';

/**
 * 
 * @export
 * @interface WorkTypes
 */
export interface WorkTypes {
    /**
     * 
     * @type {WorkTypeProperty}
     * @memberof WorkTypes
     */
    'data'?: WorkTypeProperty;
    /**
     * 
     * @type {WorkTypesMeta}
     * @memberof WorkTypes
     */
    'meta'?: WorkTypesMeta;
}

